# This is a basic workflow to help you get started with Actions

name: Hey DD32 Your Rock EH!

  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Total pwnage"
